server:
  port: 8081
  servlet:
    context-path: /api


spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.jdbc.batch_size: 10
    hibernate.order_inserts : true

  datasource:
    url: "jdbc:postgresql://localhost:5432/order_mgmt"
    username: postgres
    password: postgres
  application:
    name: opm-bulk

logging:
  file.name: log/dev_opm-bulk.log
  level:
    com.eop.order: DEBUG

